name: Continuous Integration

on:
    pull_request:
        branches: [main, develop]
env:
    PNPM_CACHE_FOLDER: .pnpm-store

jobs:
    commitlint:
        name: Commitlint - Validate commit messages
        runs-on: ${{ matrix.os }}
        timeout-minutes: 5
        strategy:
            matrix:
                node-version: [14.x]
                pnpm-version: [6.x]
                os: [ubuntu-latest]
        steps:
            - name: Checkout to ${{ github.repository  }} repository
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0

            - name: Use Node.js version ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Cache Node.js modules with pnpm
              uses: actions/cache@v2
              with:
                  path: ${{ env.PNPM_CACHE_FOLDER }}
                  key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-

            - name: Use pnpm version ${{ matrix.pnpm-version }}
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: ${{ matrix.pnpm-version }}
                  run_install: true

            - name: Validating commit messages with commitlint
                # uses pnpm to run commitlint on messages
              run: pnpm lint:commit

            # Existing config that runs with marketplace github action
            #   uses: wagoid/commitlint-github-action@v4
            #   with:
            #       configFile: commitlintrc.js
            #       # this may not be necessary but is suppose to help from getting errors
            #       # on prior commits before adding this feature
            #       firstParent: true
            #       failOnWarnings: true
            #       helpURL: https://github.com/terminal-nerds/terminal-nerd/wiki/%F0%9F%92%8C-Git-commits-convention
            #       token: ${{ github.token }}
