name: Linting

on:
    pull_request:
        branches: [main, develop]
        types: [ready_for_review]

env:
    NODE_ENV: continuous-integration
    NODE_CACHE_FOLDER: node_modules/.cache
    PNPM_CACHE_FOLDER: .pnpm-store

jobs:
    commitlint:
        name: commitlint - validate commit messages
        runs-on: ${{ matrix.os }}
        timeout-minutes: 5
        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [lts/*]
                pnpm-version: [6]
        steps:
            - name: Checkout to ${{ github.repository }}
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0

            - name: Use Node.js version ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Cache Node.js dependencies with pnpm
              uses: actions/cache@v2
              with:
                  path: ${{ env.PNPM_CACHE_FOLDER }}
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-

            - name: Use pnpm version ${{ matrix.pnpm-version }}
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: ${{ matrix.pnpm-version }}
                  run_install: true

            - name: Execute commitlint
              run: >
                  pnpm commitlint
                  --from HEAD~${{ github.event.pull_request.commits }}
                  --to HEAD
                  --verbose

    prettier:
        name: Prettier - check code formatting style
        runs-on: ${{ matrix.os }}
        timeout-minutes: 5
        strategy:
            matrix:
                node-version: [lts/*]
                pnpm-version: [6]
                os: [ubuntu-latest]
        steps:
            - name: Checkout to ${{ github.repository }}
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0

            - name: Use Node.js version ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Cache Node.js dependencies with pnpm
              uses: actions/cache@v2
              with:
                  path: ${{ env.PNPM_CACHE_FOLDER }}
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-

            - name: Use pnpm version ${{ matrix.pnpm-version }}
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: ${{ matrix.pnpm-version }}
                  run_install: true

            - name: Execute Prettier script
              run: >
                  pnpm pretty-quick
                  --branch HEAD~${{ github.event.pull_request.commits }}
                  --check
                  --verbose

    markdownlint:
        name: markdownlint - validate markdown files
        runs-on: ${{ matrix.os }}
        timeout-minutes: 5
        strategy:
            matrix:
                node-version: [lts/*]
                pnpm-version: [6]
                os: [ubuntu-latest]
        steps:
            - name: Print
              run: echo "${{ github.event.pull_request.files }} ${{ github.event.pull_request.commits }}"

            - name: Checkout to ${{ github.repository }}
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0

            - name: Use Node.js version ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Cache Node.js dependencies with pnpm
              uses: actions/cache@v2
              with:
                  path: ${{ env.PNPM_CACHE_FOLDER }}
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-

            - name: Use pnpm version ${{ matrix.pnpm-version }}
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: ${{ matrix.pnpm-version }}
                  run_install: true

            - name: Execute markdownlint
              run: pnpm markdownlint . --ignore node_modules/

    eslint:
        name: ESLint - statically analyze the JavaScript code
        runs-on: ${{ matrix.os }}
        timeout-minutes: 5
        strategy:
            matrix:
                node-version: [lts/*]
                pnpm-version: [6]
                os: [ubuntu-latest]
        steps:
            - name: Checkout to ${{ github.repository }} repository
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0

            - name: Use Node.js version ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Cache Node.js dependencies with pnpm
              uses: actions/cache@v2
              with:
                  path: ${{ env.PNPM_CACHE_FOLDER }}
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-

            - name: Cache ESLint run
              uses: actions/cache@v2
              with:
                  path: ${{ env.NODE_CACHE_FOLDER }}
                  key: ${{ runner.os }}-eslint-${{ hashFiles('**/.eslintcache') }}
                  restore-keys: ${{ runner.os }}-eslint-

            - name: Use pnpm version ${{ matrix.pnpm-version }}
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: ${{ matrix.pnpm-version }}
                  run_install: true

            - name: Execute ESLint
              run: >
                  pnpm eslint .
                  --cache
                  --cache-location node_modules/.cache/.eslintcache
                  --ext .json,.ts,.yaml,.yml,.vue
                  --format codeframe
